stages:
  - deploy

variables:
  TF_VERSION: "1.5.7"
  ARM_CLIENT_ID: $ARM_CLIENT_ID
  ARM_CLIENT_SECRET: $ARM_CLIENT_SECRET
  ARM_SUBSCRIPTION_ID: $ARM_SUBSCRIPTION_ID
  ARM_TENANT_ID: $ARM_TENANT_ID

deploy_fabric_workspace:
  stage: deploy
  tags:
    - shell-runner
  script:
    - echo "Installing Terraform version $TF_VERSION..."
    - wget https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
    - unzip terraform_${TF_VERSION}_linux_amd64.zip
    - sudo mv terraform /usr/local/bin/
    - terraform -version
    - echo "Initializing Terraform..."
    - terraform init
    - echo "Planning Terraform deployment..."
    - terraform plan
    - echo "Applying Terraform configuration..."
    - terraform apply -auto-approve
  only:
    - main
